# Cosmetics
RED := "\e[1;31m"
YELLOW := "\e[1;33m"
NC := "\e[0m"

# Shell Functions
INFO := @bash -c '\
  printf $(YELLOW); \
  echo "=> $$1"; \
  printf $(NC)' SOME_VALUE
WARNING := @bash -c '\
  printf $(RED); \
  echo "WARNING: $$1"; \
  printf $(NC)' SOME_VALUE
