# Generated by Django 2.0.2 on 2018-02-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20180226_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255),
        ),
    ]
