# Generated by Django 2.0.2 on 2018-02-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20180226_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-completed_at', 'priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed_date',
            new_name='completed_at',
        ),
    ]
